// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgzqeqCHLBe_l2M-gctc2WuCfyezpjlyQ',
    appId: '1:526600734591:web:d3a0e9eb767d38201c7c4a',
    messagingSenderId: '526600734591',
    projectId: 'sos-app-6bcd4',
    authDomain: 'sos-app-6bcd4.firebaseapp.com',
    storageBucket: 'sos-app-6bcd4.firebasestorage.app',
    measurementId: 'G-S7GGQH0WC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1KHIPRnnlmk8_C-OVDV3kpoh0GObd6y4',
    appId: '1:526600734591:android:9c5e1c7a2a8c3b881c7c4a',
    messagingSenderId: '526600734591',
    projectId: 'sos-app-6bcd4',
    storageBucket: 'sos-app-6bcd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTSUdQNteAcBjtexPB6fjcUBuM1uGDoFM',
    appId: '1:526600734591:ios:6480a1ee6f3df3201c7c4a',
    messagingSenderId: '526600734591',
    projectId: 'sos-app-6bcd4',
    storageBucket: 'sos-app-6bcd4.firebasestorage.app',
    iosBundleId: 'com.example.appmobilesos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTSUdQNteAcBjtexPB6fjcUBuM1uGDoFM',
    appId: '1:526600734591:ios:6480a1ee6f3df3201c7c4a',
    messagingSenderId: '526600734591',
    projectId: 'sos-app-6bcd4',
    storageBucket: 'sos-app-6bcd4.firebasestorage.app',
    iosBundleId: 'com.example.appmobilesos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgzqeqCHLBe_l2M-gctc2WuCfyezpjlyQ',
    appId: '1:526600734591:web:d36d5a1f11ed4ace1c7c4a',
    messagingSenderId: '526600734591',
    projectId: 'sos-app-6bcd4',
    authDomain: 'sos-app-6bcd4.firebaseapp.com',
    storageBucket: 'sos-app-6bcd4.firebasestorage.app',
    measurementId: 'G-VFCSLJLL7E',
  );
}